kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
# make sure sidecar or csi-node-daemonset deployed on 10.206.7.17
  nodeName: 10.206.7.17
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
       claimName: cfs-pvc
  containers:
    - name: pv-container
      image: nginx
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html111"
          name: pv-storage
